### ISSUE TITLE
Problem with zsh

### ISSUE THREAD

**Issue by TaylanTatli** [irevenko/tsukae#1]
This [line](https://github.com/irevenko/tsukae/blob/main/shell/parser.go#L55) was creating problem for me.   
Error message: `panic: runtime error: index out of range [1] with length 1`  

changing  
`historySlice[i] = commandSlice[1] //writing command name after sudo`  
to  
`historySlice[i] = commandSlice[0] //writing command name after sudo`  
solved problem for me.  

I don't have any programming language knowledge but i guess it's because of previous for loop, that remove timestamps.

**Comment by ttys3** [comment]
Yeah, I also got a panic 

```shell
❯ tsukae zsh
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/irevenko/tsukae/shell.ParseZshHistory(0x7a20c0, 0x0, 0x0)
        /home/xxxx/go/pkg/mod/github.com/irevenko/tsukae@v0.0.0-20210226203946-0557ed5273bd/shell/parser.go:55 +0x5c5
github.com/irevenko/tsukae/cmd.GetShellCommandsUsage(0x60cdb7, 0x3, 0x7, 0x4, 0x3, 0xc000128260, 0xc000153d68, 0x55c1e5, 0xc000140500)
        /home/xxxx/go/pkg/mod/github.com/irevenko/tsukae@v0.0.0-20210226203946-0557ed5273bd/cmd/shell_name.go:15 +0x110
github.com/irevenko/tsukae/cmd.glob..func2(0x76d500, 0x7a0d38, 0x0, 0x0)
        /home/xxxx/go/pkg/mod/github.com/irevenko/tsukae@v0.0.0-20210226203946-0557ed5273bd/cmd/commands.go:47 +0x1bf
github.com/spf13/cobra.(*Command).execute(0x76d500, 0x7a0d38, 0x0, 0x0, 0x76d500, 0x7a0d38)
        /home/xxxx/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x76da00, 0xc000000180, 0xc000153f78, 0x406e85)
        /home/xxxx/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/xxxx/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        /home/xxxx/go/pkg/mod/github.com/irevenko/tsukae@v0.0.0-20210226203946-0557ed5273bd/main.go:12 +0x36
```

**Comment by irevenko** [comment]
@TaylanTatli @ttys3 can you send me your ```.zsh_history``` snippet?

**Comment by irevenko** [comment]
Maybe your zsh configs are different since i use oh-my-zsh. But yea i need to figure out history file parsing details

**Comment by ttys3** [comment]
```shell
❯ tail .zsh_history
: 1614438637:0;sudo systemctl start gdm
: 1614438660:0;z clash
: 1614438660:0;./show.sh
: 1614438664:0;./show.sh
: 1614438697:0;tail .zsh_history
: 1614438722:0;tsukae
: 1614438726:0;tsukae -l
: 1614438729:0;tsukae zsh
: 1614438738:0;tail .zsh_history
```

**Comment by Cons-Cat** [comment]
I got this same issue on Zsh. It worked for me using Bash, though.

**Comment by irevenko** [comment]
must be my mistake, probably did parsing wrong 🤔

**Comment by TaylanTatli** [comment]
```bash
: 1614464013:0;cd Development
: 1614464013:0;ls
: 1614464019:0;ls Gits
: 1614464527:0;cd tsukae
: 1614464527:0;ls
: 1614464532:0;vim shell/parser.go
: 1614464631:0;tsukae
: 1614464634:0;tsukae zsh
: 1614464653:0;cat .zsh_history
: 1614464690:0;tail .zsh_history
```

**Comment by Anunayj** [comment]
I have the same issue and here's some snippets from mine. (might be more useful since it has sudo commands and a annoying ;
```
: 1614037600:0;git clone https://github.com/BrandomRobor/btusb-210681-fix
: 1614037608:0;cd btusb-210681-fix
: 1614037609:0;ls
: 1614037613:0;makepkg
: 1614037813:0;ls
: 1614037822:0;sudo pacman -U btusb-210681-fix-5.10.16-1-x86_64.pkg.tar.zst
: 1614469896:0;echo "hello;"
```

**Comment by Anunayj** [comment]
woops seems like someone has a rouge sudo in their .zsh_hostory
```
: 1612564513:0;sudo
```

**Comment by Anunayj** [comment]
P.S. This is not a zsh specific issue and can be fixed easily by using
```go
if len(commandSlice) == 1{
    historySlice[i] = "sudo" // Call the command sudo if there is nothing after it.
}else{
    historySlice[i] = commandSlice[1] //writing command name after sudo
}
```
P.P.S I hate go, wdym by `imported and not used: "fmt"` ITS MY CHOICE IF I WANT TO DO THAT.

**Comment by 5nord** [comment]
I had this panic due to a multi-line containing a colon, but no semi-colon. See #4 for details.

**Comment by irevenko** [comment]
> woops seems like someone has a rouge sudo in their .zsh_hostory
> 
> ```
> : 1612564513:0;sudo
> ```

@Anunayj 

Working on lonely ```sudo``` handling

**Comment by irevenko** [comment]
@TaylanTatli @ttys3 @EPonyA @Anunayj 
🔧 Probably Fixed this one in https://github.com/irevenko/tsukae/commit/1cd14cb77d7ceaa019130792b31209232aa43210
Can you try it out again?

**Comment by TaylanTatli** [comment]
> @TaylanTatli @ttys3 @EPonyA @Anunayj
> wrench Probably Fixed this one in [1cd14cb](https://github.com/irevenko/tsukae/commit/1cd14cb77d7ceaa019130792b31209232aa43210)
> Can you try it out again?

It's working for me.

**Comment by Cons-Cat** [comment]
Works for me, too! This is awesome

**Comment by irevenko** [comment]
Thanks everyone for participating in this issue! 👏
