### ISSUE TITLE
Feature: Configurable colors, and 256-color or maybe even 24-bit color (to support colorblind-friendly palette)

### ISSUE THREAD

**Issue by zachriggle** [irevenko/tsukae#11]
### Configurable Color Palette

I am red-green colorblind, so it makes it very hard to distinguish between some of the sections in the pie chart mode.  So first, it would be nice to be able to configure which colors are used (ANSI "green" and "yellow" are indistinguishable to me).  There are a few colors that aren't used (and even then there's the bold variants and background-color variants).

For example, here I cannot tell the difference between the `gc` and `verify-fix` slices in this picture:

<img width="480" alt="Screen Shot 2021-03-04 at 1 17 23 PM" src="https://user-images.githubusercontent.com/111640/110010150-ff75c880-7ceb-11eb-8720-732b30c73863.png">

It would be nice to be able to specify the set of colors used by `tsukae`.

### Stretch Goals

It would be even better if tsukae were to support 256 colors, or even 24-bit color, since most terminals support this now.  It seems there is even a Go package to provide this support, with https://github.com/gdamore/tcell.

You can check if your terminal supports 24-bit color with the following command:

<details>

```
awk 'BEGIN{
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
    for (colnum = 0; colnum<77; colnum++) {
        r = 255-(colnum*255/76);
        g = (colnum*510/76);
        b = (colnum*255/76);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
}'
```
</details>

**Comment by irevenko** [comment]
Yeaaaa, that's something i need to work on!

**Comment by irevenko** [comment]
https://github.com/gizak/termui colors are limited so can't afford this feature
