### ISSUE TITLE
Feature: Configurable command blacklist

### ISSUE THREAD

**Issue by zachriggle** [irevenko/tsukae#12]
Tsukae is great and does right what it says on the tin.  However, I don't necessarily care about my usage of e.g. `cd` or `echo`.

It would be nice if Tsukae had a configurable blacklist of commands to NOT show.  Maybe have a list of commands to ignore in e.g. `~/.config/tsukae/blacklist`.

**Comment by irevenko** [comment]
oof dude such a brilliant idea, thanks i'll implement this!

**Comment by irevenko** [comment]
Added such feature in this commit: https://github.com/irevenko/tsukae/commit/65642a855c4108c4f60d20b84c124598ae2e45ff 🎉
