### ISSUE TITLE
Cannot select text displayed by Tsukae

### ISSUE THREAD

**Issue by zachriggle** [irevenko/tsukae#13]
I'm on macOS, using iTerm2, and it appears that I cannot select the text printed out by Tsukae, to e.g. copy paste the contents somewhere else.  

When I try extra hard, iTerm2 shows me the following warning:

<img width="789" alt="Screen Shot 2021-03-04 at 5 43 46 PM" src="https://user-images.githubusercontent.com/111640/110040681-327e8300-7d11-11eb-9167-d1cb3964c532.png">

**Comment by irevenko** [comment]
It is because of the package that i'm using.
https://github.com/gizak/termui
