### ISSUE TITLE
Documentation notes

### ISSUE THREAD

**Issue by brentstewart** [irevenko/tsukae#15]
Cool project!  Thanks for sharing.  I have some ideas to improve the readme - I hope these are helpful.
1) I haven't used go, so it wasn't obvious to use __go build__.  Might want to replace the suggested __go run main.go__ with __go build__ in the description (also assumes go is installed).
2) The _blacklist_ file wasn't automatically created for me.  I just used __mkdir ~/.config/tsukae__ and then __touch blacklist__.

Thanks!

**Comment by irevenko** [comment]
Thanks for your feedback, gonna fix these

**Comment by irevenko** [comment]
@brentstewart 
I've fixed automatic blacklist creation can you try it again?

**Comment by brentstewart** [comment]
@irevenko - Works!   Pulled the change, deleted my _blacklist_ file and the directory.  Re-built and ran and it created the directory and file.  Wrote a short article about your app on my blog (https://www.nextpertise.net/posts/210306_tsukae) where it will be seen by tens of visitors :) .  Best wishes!
