### ISSUE TITLE
Feature request: would like tsukae to ignore specified commands

### ISSUE THREAD

**Issue by kebeda** [irevenko/tsukae#16]
I would like to be able to pass certain commands to be ignored when displaying the charts, i.e. the number of times I invoke `git` or `ls` or `cd` is not as important to me as other commands, but these are typically at the top of the charts, crowding them out. Maybe a command line option that takes one or more commands (or repeat the option) to be eliminated from the final list?

**Comment by irevenko** [comment]
Read the README
https://github.com/irevenko/tsukae#ignore-commands-by-writing-the-to-blacklist-file
