### ISSUE TITLE
Doesn't work on macOS

### ISSUE THREAD

**Issue by heapcrash** [irevenko/tsukae#2]
Not sure what the issue is, $HOME and $HISTFILE are all set correctly.  The file is accessible and readable.

```
$ echo $HOME
/Users/heapcrash

$ echo $HISTFILE
/Users/heapcrash/.zhistory

$ tail -2 $HISTFILE
: 1614405148:0;echo $HISTFILE
: 1614405182:0;tail -2 $HISTFILE

$ go run main.go zsh
2021/02/27 00:52:12 Can't find or open /.zsh_history in: /Users/heapcrash
exit status 1
```

**Comment by irevenko** [comment]
Oh, I see your file is called ```.zhistory``` I'll fix this one today. Can you also send me a small snippet of your zhistory file?

**Comment by dm9pZCAq** [comment]
for me `$HISTFILE` is `~/.cache/zsh/history`

i think firstly it should get path to history file from `$HISTFILE` environment variable and then if it unset use default history paths

**Comment by heapcrash** [comment]
@irevenko There is a small snippet in the original post, but I'll copy here for visibility:

```
: 1614405148:0;echo $HISTFILE
: 1614405182:0;tail -2 $HISTFILE
```

**Comment by irevenko** [comment]
> for me `$HISTFILE` is `~/.cache/zsh/history`
> 
> i think firstly it should get path to history file from `$HISTFILE` environment variable and then if it unset use default history paths

@dm9pZCAq 
Somehow i can't get this env var using Go :(

```go
package main

import (
    "fmt"
    "os"
)

func main() {
    fmt.Println(os.Getenv("HISTFILE"))
}
```

**Comment by dm9pZCAq** [comment]
it is because you variable seted from `rc` but not exported

you can see all exported variables with: 
```sh
printenv | sed -n '/^HISTFILE/p'
```

so you can add to readme something like that:
````markdown
if you have custom `HISTFILE` you need to export it from you `rc` file

`~/.zshrc`:
```zsh
# ...
export HISTFILE=~/.cache/zsh/history
# ...
```
````

or you can add command line option to specify custom `HISTFILE`

**Comment by irevenko** [comment]
What i'll do is i will provide a flag for entering history file manually, and also i'll check for ```HISTFILE``` and only then set the hist file in ```$HOME/bash or zsh hist

**Comment by irevenko** [comment]
@heapcrash 
🔧 Probably fixed this one in https://github.com/irevenko/tsukae/commit/f661b8cc6746d4ffb0dbe0792203fc6c865f0bd8
Can you try it out again?

Now it checks for ```$HISTFILE``` and also added flag to manually specify the hist file

**Comment by heapcrash** [comment]
Does not seem to work:

```
$ echo $HISTFILE
/Users/heapcrash/.zhistory

$ go run main.go zsh
2021/03/03 14:58:22 Can't find or open /.zsh_history in: /Users/heapcrash
Specify absolute hist file path: -m=/your_dir/your_hist_file
exit status 1

$ go run main.go zsh -m=$HISTFILE
Error: unknown shorthand flag: 'm' in -m=/Users/zachriggle/.zhistory
```

**Comment by irevenko** [comment]
1) HISTFILE must be set as variable in your ```.bashrc``` or ```.zshrc```
like ```export HISTFILE=your_path```
2) the flag for manual history specification is oops ```-s```
