### ISSUE TITLE
binary releases

### ISSUE THREAD

**Issue by dwvisser** [irevenko/tsukae#7]
I would love to see a snap or .deb package of this for easy installation on my Ubuntu systems. 😄

**Comment by irevenko** [comment]
🤔 yea. i'll do this after adding ```fish shell``` support

**Comment by cubercsl** [comment]
I may package it in AUR first for archlinux user.

**Comment by irevenko** [comment]
@2014CAIS01 that's would be dope!

**Comment by cubercsl** [comment]
> @2014CAIS01 that's would be dope!

okey, it is now available in [AUR](https://aur.archlinux.org/packages/tsukae-git/). Maybe it can be added to the README.

**Comment by irevenko** [comment]
thanks

**Comment by irevenko** [comment]
easy way of installation.
1) Install Go https://golang.org/dl/
2) Run ```go get -u github.com/irevenko/tsukae```
3) you can use ```tsukae```
