### ISSUE TITLE
Unable to parse history files with at timestamp written to them (HISTTIMEFORMAT set)

### ISSUE THREAD

**Issue by kebeda** [irevenko/tsukae#8]
bash or zsh history files that have timestamps written into them cannot be parsed.

```
2021/03/03 14:19:20 <COMMANDS_NUMBER> must be an Integer
exit status 1

```

**Comment by irevenko** [comment]
can you link your history file?

**Comment by kebeda** [comment]
I can...here are some samples

.bash_history:
```
#1582740627
cd ~/Documents
#1582740632
cd ~/Music
#1582740635
cd ~/Pictures
#1582740655
cd ~/Downloads/
```
.zsh_history:
```
: 1598619692:0;cd ~/Documents
: 1604498104:0;cd ~/Music
: 1605828979:0;cd ~/Pictures
: 1613054973:0;cd ~/Downloads
```

**Comment by irevenko** [comment]
zsh should be ok, what command are you executing?
```tsukae bash 5``` ?

**Comment by kebeda** [comment]
Both bash and zsh fail with the exact same error:
```
go run main.go bash /home/kebeda/.bash_history 5
2021/03/04 12:03:26 <COMMANDS_NUMBER> must be an Integer
exit status 1
---
go run main.go zsh /home/kebeda/.zsh_history  
2021/03/04 12:04:22 <COMMANDS_NUMBER> must be an Integer
exit status 1
```

**Comment by irevenko** [comment]
command format:
```go run main.go bash 5-15```
```go run main.go zsh 5-15```

if you want to specify the file hist manually 
```go run main.go bash -s=your_path```

**Comment by irevenko** [comment]
Also i fixed this bash timestamp recognition, and now it ignores everything what starts with ```#```
